[package]
name = "rust-smpp"
version = "0.1.0"
authors = ["Mateus Silveira <mateus.silveira@zenvia.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
